### ISSUE TITLE
AttributeError in Projective-Spatial-Transformers

### ISSUE THREAD

**Issue by yqwang01** [gaocong13/Projective-Spatial-Transformers#26]
I admire your work Projective-Spatial-Transformers very much. However, I encountered some problems when testing your codes. It seems that the codes in train.py are incompatible to the module ‘geomstats’. The Error Report is as follows.

 

```
Traceback (most recent call last):

  File "train.py", line 168, in <module>

    train()

  File "train.py", line 104, in train

    riem_dist = np.sqrt(riem.loss(rtvec.detach().cpu(), rtvec_gt.detach().cpu(), METRIC))

AttributeError: module 'geomstats.geometry.riemannian_metric' has no attribute 'loss'
```

 

 

What should I do to solve this bug? Looking forward to your early reply. Thanks.

**Comment by gaocong13** [comment]
geomstats is a fast evolving package. The API has been changed a lot. You can check out this function: https://geomstats.github.io/api/geometry.html#geomstats.geometry.riemannian_metric.RiemannianMetric.dist. I suggest revising line 104 to be:
`riem_dist = riem.dist(rtvec.detach().cpu(), rtvec_gt.detach().cpu())`

**Comment by yqwang01** [comment]
Thanks for your reply in time. 
I changed line 104 into  `riem_dist = RiemMetric.dist(rtvec.detach().cpu(), rtvec_gt.detach().cpu())`. And then, I changed backend via the command `export GEOMSTATS_BACKEND=autograd` in the terminal due to `RuntimeError: Automatic differentiation is not supported with numpy backend. Use autograd, pytorch or tensorflow backend instead`. 
However, some problems still exist. 
```
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    train()
  File "train.py", line 104, in train
    riem_dist = RiemMetric.dist(rtvec.detach().cpu(), rtvec_gt.detach().cpu()) # riem_dist = np.sqrt(riem.loss(rtvec.detach().cpu(), rtvec_gt.detach().cpu(), METRIC))
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/geomstats/geometry/riemannian_metric.py", line 297, in dist
    sq_dist = self.squared_dist(point_a, point_b, **kwargs)
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/geomstats/geometry/riemannian_metric.py", line 274, in squared_dist
    log = self.log(point=point_b, base_point=point_a, **kwargs)
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/geomstats/geometry/connection.py", line 188, in log
    res = minimize(
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 696, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_lbfgsb_py.py", line 305, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 332, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 76, in __call__
    self._compute_if_needed(x, *args)
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 70, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/geomstats/_backend/autograd/autodiff.py", line 145, in func_with_grad
    value = func(*args)
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/geomstats/geometry/connection.py", line 179, in objective
    velocity = gs.cast(velocity, dtype=base_point.dtype)
  File "/home/xxx/anaconda3/envs/xxxx/lib/python3.8/site-packages/geomstats/_backend/autograd/__init__.py", line 335, in cast
    return x.astype(dtype)
TypeError: Cannot interpret 'torch.float32' as a data type
```

Besides, it seems that line 110 in train.py, `riem_grad = riem.grad(rtvec.detach().cpu(), rtvec_gt.detach().cpu(), METRIC)`, is not correct. I checked the geomstats.geometry.riemannian_metric.py, and found that Class RiemannianMetric doesn't possess a method named 'grad'. 

I'm not familiar with the module 'geomstats', so I'm not capable of revising these bugs independently. Your generous assistance will be highly appreciated. Thanks again for your time.

**Comment by gaocong13** [comment]
Hi Yiqing,

I recommend you step back to use the version geomstats==2.2.1. I have looked into their latest version as well, and I encountered the same issues you have observed. I don't have enough time right now to match my implementations to their new APIs.

I also recommend downgrading numpy to numpy-1.21.6. You may encounter conflicts using the latest numpy. Let me know how it goes.

**Comment by yqwang01** [comment]
Hi Cong Gao,

Thanks for your reply. I have reinstalled "geomstats" and "numpy" as you advised, and it works! I'm testing your example codes, and there have been no errors so far. Thanks again for your time. You really help me a lot.
