### ISSUE TITLE
RuntimeError about train.py

### ISSUE THREAD

**Issue by sakilohale** [gaocong13/Projective-Spatial-Transformers#34]
Hi sir, I wonder if you'll be able to answer some basic questions after all this time.

I meet a Runtime Error when I run the train.py file.

sometimes I will get RuntimeError: Trying to create tensor with negative dimension -9223372036854775808: [2, 128, 128, -9223372036854775808, 4], or RuntimeError: unsupported range: nan -> nan. I guess there is a problem in ProST.

Details are as follows.

Traceback (most recent call last):
  File "/home/shu/ljy/PST_EDIT/src/train.py", line 189, in <module>
    train()
  File "/home/shu/ljy/PST_EDIT/src/train.py", line 112, in train
    encode_mov, encode_tar, proj_mov = model(_3D_vol, target, rtvec, corner_pt)
  File "/home/shu/anaconda3/envs/ljy/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shu/ljy/PST_EDIT/src/module.py", line 276, in forward
    self.src, self.det, self.pix_spacing, self.step_size, False)
RuntimeError: unsupported range: nan -> nan

![image](https://github.com/gaocong13/Projective-Spatial-Transformers/assets/69140607/93c52b72-b47f-4abf-999d-87b6c13cca59)

I would appreciate it if you could see it and answer it.

**Comment by sakilohale** [comment]
test.py and test_regi.py are fine. I get this error only when training.

**Comment by sakilohale** [comment]
when training, dist_min and dist_max would be nan sometimes.
In the original code, dist_min, dist_max = raydist_range(transform_mat3x4, corner_pt, self.src).
Maybe there are some compute errors in this function.

**Comment by cong-code** [comment]
Hi, I also encountered this problem, have you solved it?
