### ISSUE TITLE
Run on Windows 10 environment

### ISSUE THREAD

**Issue by decawang** [gaocong13/Projective-Spatial-Transformers#4]
hi, I notice the prerequisites is Linux or OSX.  I try to run the code under Windows 10 but not successful. Does the code can also run under the Windows environment?

**Comment by gaocong13** [comment]
Thank you for your interest. It has not been tested under windows yet, but I will try to support it on windows soon. If you would like to post the error message during your installation, I could help take a look!

**Comment by decawang** [comment]
Thanks for your prompt reply. The following is the error message after running the command: python setup.py install

(base) D:\github\slx\Projective-Spatial-Transformers\ProSTGrid>python setup.py install
running install
running bdist_egg
running egg_info
writing ProSTGrid.egg-info\PKG-INFO
writing dependency_links to ProSTGrid.egg-info\dependency_links.txt
writing top-level names to ProSTGrid.egg-info\top_level.txt
reading manifest file 'ProSTGrid.egg-info\SOURCES.txt'
writing manifest file 'ProSTGrid.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\devInstall\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'ProSTGrid' extension
Emitting ninja build file D:\github\slx\Projective-Spatial-Transformers\ProSTGrid\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\devInstall\Anaconda3\lib\site-packages\torch\include -IC:\devInstall\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\devInstall\Anaconda3\lib\site-packages\torch\include\TH -IC:\devInstall\Anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\devInstall\Anaconda3\include -IC:\devInstall\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c D:\github\slx\Projective-Spatial-Transformers\ProSTGrid\ProSTGrid_kernel.cu -o D:\github\slx\Projective-Spatial-Transformers\ProSTGrid\build\temp.win-amd64-3.7\Release\ProSTGrid_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ProSTGrid -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: D:/github/slx/Projective-Spatial-Transformers/ProSTGrid/build/temp.win-amd64-3.7/Release/ProSTGrid_kernel.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\devInstall\Anaconda3\lib\site-packages\torch\include -IC:\devInstall\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\devInstall\Anaconda3\lib\site-packages\torch\include\TH -IC:\devInstall\Anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\devInstall\Anaconda3\include -IC:\devInstall\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c D:\github\slx\Projective-Spatial-Transformers\ProSTGrid\ProSTGrid_kernel.cu -o D:\github\slx\Projective-Spatial-Transformers\ProSTGrid\build\temp.win-amd64-3.7\Release\ProSTGrid_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ProSTGrid -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:/devInstall/Anaconda3/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

C:/devInstall/Anaconda3/lib/site-packages/torch/include\ATen/record_function.h(18): warning: modifier is ignored on an enum specifier

C:/devInstall/Anaconda3/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(483): error: a member with an in-class initializer must be const

C:/devInstall/Anaconda3/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(496): error: a member with an in-class initializer must be const

C:/devInstall/Anaconda3/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(510): error: a member with an in-class initializer must be const

C:/devInstall/Anaconda3/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(523): error: a member with an in-class initializer must be const

C:/devInstall/Anaconda3/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(97): warning: modifier is ignored on an enum specifier

C:/devInstall/Anaconda3/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(126): warning: modifier is ignored on an enum specifier

C:/devInstall/Anaconda3/lib/site-packages/torch/include/torch/csrc/api/include\torch/enum.h(187): warning: statement is unreachable
          detected during instantiation of "at::Reduction::Reduction torch::enumtype::reduction_get_enum(V) [with V=torch::nn::L1LossOptions::reduction_t]"
C:/devInstall/Anaconda3/lib/site-packages/torch/include/torch/csrc/api/include\torch/nn/functional/loss.h(20): here

C:/devInstall/Anaconda3/lib/site-packages/torch/include/torch/csrc/api/include\torch/enum.h(187): warning: statement is unreachable
          detected during instantiation of "at::Reduction::Reduction torch::enumtype::reduction_get_enum(V) [with V=torch::nn::KLDivLossOptions::reduction_t]"
C:/devInstall/Anaconda3/lib/site-packages/torch/include/torch/csrc/api/include\torch/nn/functional/loss.h(64): here

4 errors detected in the compilation of "C:/Users/wangs/AppData/Local/Temp/tmpxft_00004760_00000000-10_ProSTGrid_kernel.cpp1.ii".
ProSTGrid_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\devInstall\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "C:\devInstall\Anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "C:\devInstall\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\devInstall\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\devInstall\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\devInstall\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\devInstall\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\devInstall\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\devInstall\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\devInstall\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\devInstall\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\devInstall\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "C:\devInstall\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\devInstall\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\devInstall\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\devInstall\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\devInstall\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\devInstall\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\devInstall\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\devInstall\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\devInstall\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\devInstall\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "C:\devInstall\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\devInstall\Anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\devInstall\Anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\devInstall\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\devInstall\Anaconda3\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\devInstall\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 631, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\devInstall\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\devInstall\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by gaocong13** [comment]
Hi, I am sorry for the late response. I think this error is due to the CUDA environment in windows. I encountered the same error. But the CPU version of ProST works on my windows installation. Could you try install ProST_cpuonly first? I am going to look into this CUDA problem.

However, a linux environment is recommended, since it will be much easier!
