### ISSUE TITLE
老师你好，我在运行train.py时出现这样的错误，环境基本都配置好了，不知道该错误究竟是什么原因，不知道该修改哪里？

### ISSUE THREAD

**Issue by xsk0802** [gaocong13/Projective-Spatial-Transformers#7]
(pytorch) [wzc@gpu01 src]$ python train.py
INFO: Using numpy backend
module parameters: 781723
  0%|                                                                                                                             | 0/200 [00:00<?, ?it/s]/usr/wzc/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
  0%|                                                                                                                             | 0/200 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    train()
  File "train.py", line 105, in train
    riem_dist = np.sqrt(riem.loss(rtvec.detach().cpu(), rtvec_gt.detach().cpu(), METRIC))
  File "/usr/wzc/anaconda3/envs/pytorch/lib/python3.7/site-packages/geomstats/geometry/riemannian_metric.py", line 38, in loss
    sq_dist = metric.squared_dist(y_pred, y_true)
  File "/usr/wzc/anaconda3/envs/pytorch/lib/python3.7/site-packages/geomstats/geometry/riemannian_metric.py", line 270, in squared_dist
    log = self.log(point=point_b, base_point=point_a)
  File "/usr/wzc/anaconda3/envs/pytorch/lib/python3.7/site-packages/geomstats/geometry/invariant_metric.py", line 346, in log
    if gs.allclose(base_point, identity):
  File "/usr/wzc/anaconda3/envs/pytorch/lib/python3.7/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "<__array_function__ internals>", line 6, in allclose
  File "/usr/wzc/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/numeric.py", line 2189, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 6, in isclose
  File "/usr/wzc/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/numeric.py", line 2290, in isclose
    return within_tol(x, y, atol, rtol)
  File "/usr/wzc/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/numeric.py", line 2276, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (2,6) (4,4)

**Comment by gaocong13** [comment]
Hi, thanks again for your interest. Since this will be exposed to broader community, I am replying you in English.

This issue is due to the version geomstats package. Please check the commit history on Oct.29 2020 (https://github.com/gaocong13/Projective-Spatial-Transformers/commit/8786b14de5a16eaf4877bfc052f5f3f48ec86a14). If you could follow the geomstats package import difference and double check your local files, this issue should be solved. Let me know if it still doesn't work.

**Comment by gaocong13** [comment]
This issue is caused by a recent update of "geomstats" package. SE3_Group initialization now needs to specify 'point_type='vector'. This bug is corrected by the recent commit f33a7606dec7608b7277a71e0c4a338ae271ce0e.
